### ISSUE TITLE
Huge negative space above and below the Circle video on Course page on Mobile.

### ISSUE THREAD

**Issue by jkim237** [jkim237/CDTP_Web#3]
| Safari | Chrome | Web View |
|:----------:|:----------:|:----------:|
| ![IMG_1533](https://user-images.githubusercontent.com/45983469/96883177-0fb6a500-14bb-11eb-8613-3a06b9f382df.PNG) | ![IMG_1532](https://user-images.githubusercontent.com/45983469/96883212-1c3afd80-14bb-11eb-862a-33aa71fbaacf.PNG) | ![IMG_1531](https://user-images.githubusercontent.com/45983469/96883232-2230de80-14bb-11eb-9c07-8fbe3ebac5cf.PNG) |

### But it works perfectly on the web.

**Comment by filoscoder** [comment]
This issue and #2 probably has something wrong with the media queries! 
`Assign` me these 2 issues, I'll be working on the weekend
